/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualix.print.visao;

import br.com.qualix.aaaConfig.Configuracoes;
import br.com.qualix.aaaConfig.modelo.ArquivoConfig;
import br.com.qualix.aaaConfig.servico.SArquivoConfig;
import br.com.qualix.aaaFerramentas.Pandora;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.print.DocFlavor;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;

/**
 *
 * @author Wagner
 */
public class FSelecionarImpressora extends javax.swing.JFrame {

    /**
     * Creates new form FSelecionarImpressora
     */
    public FSelecionarImpressora() {
        initComponents();
        
        try {
            iniciaTela();
        } catch (Exception e){
            Pandora.msgException(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jnmImpressoraCaixa = new EditFiled.JNumberLetterField();
        jLabel4 = new javax.swing.JLabel();
        jtpImpressoras = new javax.swing.JComboBox<>();
        jbtSalvarImpressoraCaixa = new javax.swing.JButton();
        jdsBobina = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuração de Impressora");
        setResizable(false);

        jLabel3.setText("Impressora do Caixa");

        jLabel2.setText("Nome da Impressora Atual");

        jnmImpressoraCaixa.setEditable(false);
        jnmImpressoraCaixa.setText("jNumberLetterField1");
        jnmImpressoraCaixa.setTamanhoMax(50);

        jLabel4.setText("Selecionar");

        jtpImpressoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtSalvarImpressoraCaixa.setText("Salvar");
        jbtSalvarImpressoraCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarImpressoraCaixaActionPerformed(evt);
            }
        });

        jdsBobina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "58mm", "80mm", "90mm" }));

        jLabel1.setText("Bobina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jnmImpressoraCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtpImpressoras, 0, 221, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jdsBobina, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtSalvarImpressoraCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jnmImpressoraCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtpImpressoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdsBobina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSalvarImpressoraCaixa))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalvarImpressoraCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarImpressoraCaixaActionPerformed
        try {
            
//            if (jtpImpressoras.getSelectedItem().equals(jnmImpressoraCaixa.getText())){
//                return;
//            }
            
            
            try {
                ArquivoConfig aconf = SArquivoConfig.buscaArquivo();
                Configuracoes.IMPRESSORA = (String) jtpImpressoras.getSelectedItem();
                Configuracoes.IMPRESSORA_TAM = (String) jdsBobina.getSelectedItem();
                aconf.setNmImpressora(Configuracoes.IMPRESSORA);
                aconf.setDsBobina(Configuracoes.IMPRESSORA_TAM);
                SArquivoConfig.gravaArquivo(aconf);
            } catch (Exception e) {
                
            }
//            
//            //Atualiza impressora do Caixa
//            if (jtpImpressoras.getItemCount() == 0){
//                CParametro.atualizaValor("nmImpressoraCaixa", " ");
//                throw new AlertaException("Não foi encontrada nenhuma impressora instalada no computador!");
//            }
//            if (jtpImpressoras.getSelectedIndex() < 0){
//                throw new AlertaException("É necessário informar a impressora!");
//            }
//            String nmImpressora = (String) jtpImpressoras.getSelectedItem();
//            if (jtpImpressoras.getSelectedIndex() != 0){
//                CParametro.atualizaValor("nmImpressoraCaixa", nmImpressora);
//            } else {
//                CParametro.atualizaValor("nmImpressoraCaixa", " ");
//            }
//            //Fim impressora Caixa
//                

            
            //buscarImpressoras();
            dispose();
        } catch (Exception e){
            Pandora.msgException(e);
        }
    }//GEN-LAST:event_jbtSalvarImpressoraCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FSelecionarImpressora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FSelecionarImpressora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FSelecionarImpressora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FSelecionarImpressora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FSelecionarImpressora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtSalvarImpressoraCaixa;
    private javax.swing.JComboBox<String> jdsBobina;
    private EditFiled.JNumberLetterField jnmImpressoraCaixa;
    private javax.swing.JComboBox<String> jtpImpressoras;
    // End of variables declaration//GEN-END:variables

    private void iniciaTela() throws Exception {
        carregaImpressoras();
        buscarImpressoras();
        this.setTitle(this.getTitle());
        
        try {
            this.setIconImage(Configuracoes.LOGO_SISTEMA);
        } catch (Exception e) {
            
        }
        
    }

    private void carregaImpressoras() {
        jtpImpressoras.removeAllItems();
        PrintService[] ps = PrintServiceLookup.lookupPrintServices(null, null);
        jtpImpressoras.addItem("Nenhuma Impressora");
        for (PrintService p : ps) {
            jtpImpressoras.addItem(p.getName());
        }
    }
    
    
    private void buscarImpressoras() throws SQLException{
        
        //Busca impressora do Caixa
        int occ = 0;
        
        
        try {
            ArquivoConfig aconf = SArquivoConfig.buscaArquivo();
            Configuracoes.IMPRESSORA = aconf.getNmImpressora();
            Configuracoes.IMPRESSORA_TAM = aconf.getDsBobina();
        } catch (Exception e) {
                
        }
        
        
        
        String nmImpCaixa = Configuracoes.IMPRESSORA;
        String dsTamImpCaixa = Configuracoes.IMPRESSORA_TAM;
        if (nmImpCaixa != null){
            jnmImpressoraCaixa.setText(nmImpCaixa);
        } else {
            jnmImpressoraCaixa.setText(" ");
        }
        for (int i = 0; i < jtpImpressoras.getItemCount(); i++) {
            if (jtpImpressoras.getItemAt(i).equals(nmImpCaixa)){
                occ = i;
            }
        }
        jtpImpressoras.setSelectedIndex(occ);
        
        
        for (int i = 0; i < jdsBobina.getItemCount(); i++) {
            if (jdsBobina.getItemAt(i).equals(dsTamImpCaixa)){
                occ = i;
            }
        }
        jdsBobina.setSelectedIndex(occ);
        //Fim Busca impressora do Caixa
        
    }
    
}
