/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualix.print.visao;

import br.com.qualix.aaaConfig.Configuracoes;
import br.com.qualix.aaaException.AlertaException;
import br.com.qualix.aaaFerramentas.FLoad;
import br.com.qualix.aaaFerramentas.Pandora;
import br.com.qualix.print.modelo.CapsulePrint;
import br.com.qualix.print.servico.PP2;
import br.com.qualix.print.servico.Relatorio;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Wagner
 */
public class FSimulaPrint extends javax.swing.JDialog {

    /**
     * Creates new form FSimulaPrint
     */
    
    String dsTexto = "";
    CapsulePrint capsule = null;
    
    public FSimulaPrint(CapsulePrint capsulePrint, Map map) {
    
        
        initComponents();
//        if (Configuracoes.IMPRESSORA_TAM.equals("90")){
//            this.setResizable(true);
//            this.setSize(getSize().width + 300, getSize().height);
//            repaint();
//        }
        
        capsule = capsulePrint;
        if (map != null){
            dsTexto = (String) map.get("texto");
            String dsTextoAlt = dsTexto;
            dsTextoAlt = dsTextoAlt.replace("M1", "");
            dsTextoAlt = dsTextoAlt.replace("M0", "");
            dsTextoAlt = dsTextoAlt.replace("\u001B!\u0001", "");
            
            
            //texto += "" + "!" + "";
            
            jpaper.setText(dsTextoAlt);
            
            if (map.get("edit").equals("NOEDIT")){
                jpaper.setEnabled(false);
            } else {
                jpaper.setEnabled(true);
            }
        }
        
        
        try {
//            String impressora = CParametro.returnValor("nmImpressoraCaixa");
            String impressora = "PRINT";
            if (impressora.equals(" ")){
                jButton1.setEnabled(false);
            }
        } catch (Exception e){
            Pandora.msgException(e);
        }
        
        try {
            this.setIconImage(Configuracoes.LOGO_SISTEMA);
        } catch (Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpaper = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pré-Impressão");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                showw(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                show(evt);
            }
        });

        jpaper.setBackground(new java.awt.Color(255, 255, 204));
        jpaper.setColumns(20);
        jpaper.setRows(5);
        jScrollPane1.setViewportView(jpaper);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/printTermic32.png"))); // NOI18N
        jButton1.setText("Cupom");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/print.png"))); // NOI18N
        jButton2.setText("Sulfite");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //avancado direto na impressora
        try {
            if (Configuracoes.IMPRESSORA == null || Configuracoes.IMPRESSORA.equals("") || Configuracoes.IMPRESSORA.equals(" ") || Configuracoes.IMPRESSORA.equals("  ")){
                throw new AlertaException("Impressora não encontrada! Acesse CONFIGURAÇÕES e configure a impressora.");
            }
            
            PP2.paraImpressora(dsTexto);
            //PP2.paraImpressora(jpaper.getText());
        } catch (Exception e) {
            Pandora.ex(e);
        }
        //PP2.paraImpressora(dsTexto);
        
//        tiraF();
//        FLoad faguarde = new FLoad();
//        Thread t = new Thread() {
//            public void run() {
//                faguarde.setVisible(true);
//                try {
//                    Map map = new HashMap();
//                    //map.put("EMPRESA", Session.SESSION_DSTITULORELATORIO);
//                    map.put("TITLE", "");
//                    map.put("SUBTITLE", "");
//                    map.put("text", jpaper.getText());
//                    ArrayList<Object> list = new ArrayList<>();
//                    list.add("o");
//                    //dispose();
//                    Relatorio.print(list, map, "RCupomA4");
//                } catch (Exception ex) {
//                    faguarde.dispose();
//                    Pandora.msgInfo("Erro ao abrir Relatório\n" + ex.getMessage());
//                }
//                faguarde.dispose();
//            }
//        };
//        t.start();
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void tiraF(){
        if (this.isModal()){
            this.setModal(false);
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tiraF();
        
        if (capsule == null){
            FLoad faguarde = new FLoad();
            Thread t = new Thread() {
                public void run() {
                    faguarde.setVisible(true);
                    try {
                        Map map = new HashMap();
                        //map.put("EMPRESA", Session.SESSION_DSTITULORELATORIO);
                        map.put("TITLE", "");
                        map.put("SUBTITLE", "");
                        map.put("text", jpaper.getText());
                        ArrayList<Object> list = new ArrayList<>();
                        list.add("o");
                        //dispose();
                        Relatorio.print(list, map, "RCupomA4");
                    } catch (Exception ex) {
                        faguarde.dispose();
                        Pandora.msgInfo("Erro ao abrir Relatório\n" + ex.getMessage());
                    }
                    faguarde.dispose();
                }
            };
            t.start();
            
        } else {
            FLoad faguarde = new FLoad();
            Thread t = new Thread() {
                public void run() {
                    faguarde.setVisible(true);
                    try {
                        Relatorio.print(capsule.getLista(), capsule.getParams(), capsule.getDsCaminho());
                    } catch (Exception ex) {
                        faguarde.dispose();
                        Pandora.msgInfo("Erro ao abrir Relatório\n" + ex.getMessage());
                    }
                    faguarde.dispose();
                }
            };
            t.start();
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void show(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_show
        
    }//GEN-LAST:event_show

    private void showw(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_showw
        
    }//GEN-LAST:event_showw

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FSimulaPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FSimulaPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FSimulaPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FSimulaPrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FSimulaPrint(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jpaper;
    // End of variables declaration//GEN-END:variables
}
