/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualix.aaaMain;

import br.com.qualix.aaaConfig.Configuracoes;
import br.com.qualix.aaaConfig.modelo.ArquivoConfig;
import br.com.qualix.aaaConfig.servico.SArquivoConfig;
import br.com.qualix.aaaConfig.visao.FConfiguracoes;
import br.com.qualix.aaaConfig.visao.FSobre;
import br.com.qualix.aaaFerramentas.Pandora;
import br.com.qualix.orcamento.visao.FIPedido;
import br.com.qualix.orcamento.visao.FRelatorioVendas;
import br.com.qualix.pequenoprincipe.visao.FVenda;
import br.com.qualix.pessoa.modelo.Pessoa;
import br.com.qualix.pessoa.servico.SPessoa;
import br.com.qualix.pessoa.visao.FIPessoa;
import br.com.qualix.pessoa.visao.FIPessoinha;
import br.com.qualix.pessoa.visao.FPessoa;
import br.com.qualix.print.visao.FSelecionarImpressora;
import br.com.qualix.proserv.modelo.Grupo;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import keeptoo.KGradientPanel;

/**
 *
 * @author Wagner
 */
public class FBackground5 extends javax.swing.JFrame {

    FIPedido boxPedido = null;
    FIPessoa boxPessoa = null;
    FIPessoinha boxPessoinha = null;

    /**
     * Creates new form Background3
     */
    public FBackground5(String sku) {
        initComponents();

        String image = "back04"; //Padrão Azul Claro
//        
        String[] versao = sku.split("-");

        if (sku != null) {
            if (versao[2].equals("1")) {
                image = "back02"; //Azul escuro
            } else if (versao[2].equals("2")) {
                image = "back06"; //Moderno Verde e Azul
            } else if (versao[2].equals("3")) {
                image = "back07"; //Amarelo pintura
            } else if (versao[2].equals("4")) {
                image = "back05"; //Amarelo pintura
            }
        }
        Icon imagem = new ImageIcon(getClass().getResource("/assets/" + image + ".jpg")); //Azul claro

        //Altera a imagem do fundo
        //Icon imagem = new ImageIcon(getClass().getResource("/assets/back04.jpg")); //Azul claro
        //Icon imagem = new ImageIcon(getClass().getResource("/assets/back02.jpg")); //Azul escuro
        //Icon imagem = new ImageIcon(getClass().getResource("/assets/back06.jpg")); //Moderno verde azul
        //Icon imagem = new ImageIcon(getClass().getResource("/assets/back07.jpg")); //Amarelo
        JLabel lab = new JLabel();
        lab.setIcon(imagem);
        double alt = Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        double larg = Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        int altura = (int) alt;
        int largura = (int) larg;
        lab.setBounds(0, 0, largura, altura);
        jDesktopPane1.add(lab);

        try {
            inicia();
        } catch (Exception e) {
            Pandora.ex(e);
        }

        try {
            this.setIconImage(Configuracoes.LOGO_SISTEMA);
        } catch (Exception e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        jbtModulos = new javax.swing.JButton();
        jbtCadEmpresa1 = new javax.swing.JButton();
        jbtNone2 = new javax.swing.JButton();
        jbtNone3 = new javax.swing.JButton();
        jbtNone4 = new javax.swing.JButton();
        jbtNone5 = new javax.swing.JButton();
        jbtNone6 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistefácil - Wagner (44) 9 9876-5432");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                onShow(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        jbtModulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/shop_cart_64.png"))); // NOI18N
        jbtModulos.setText("Venda");
        jbtModulos.setAlignmentY(0.9F);
        jbtModulos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtModulos.setFocusable(false);
        jbtModulos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtModulos.setMargin(new java.awt.Insets(5, 25, 5, 25));
        jbtModulos.setMaximumSize(new java.awt.Dimension(130, 96));
        jbtModulos.setPreferredSize(new java.awt.Dimension(130, 99));
        jbtModulos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModulosActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtModulos);

        jbtCadEmpresa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/atend2_64.png"))); // NOI18N
        jbtCadEmpresa1.setText("Empresa");
        jbtCadEmpresa1.setAlignmentY(0.9F);
        jbtCadEmpresa1.setFocusable(false);
        jbtCadEmpresa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtCadEmpresa1.setMargin(new java.awt.Insets(5, 25, 5, 25));
        jbtCadEmpresa1.setMaximumSize(new java.awt.Dimension(130, 96));
        jbtCadEmpresa1.setPreferredSize(new java.awt.Dimension(130, 99));
        jbtCadEmpresa1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtCadEmpresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadEmpresa1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtCadEmpresa1);

        jbtNone2.setAlignmentY(0.9F);
        jbtNone2.setEnabled(false);
        jbtNone2.setFocusable(false);
        jbtNone2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNone2.setMargin(new java.awt.Insets(5, 25, 5, 25));
        jbtNone2.setPreferredSize(new java.awt.Dimension(130, 99));
        jbtNone2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNone2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtNone2);

        jbtNone3.setAlignmentY(0.9F);
        jbtNone3.setEnabled(false);
        jbtNone3.setFocusable(false);
        jbtNone3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNone3.setMargin(new java.awt.Insets(5, 25, 5, 25));
        jbtNone3.setPreferredSize(new java.awt.Dimension(130, 99));
        jbtNone3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNone3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNone3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtNone3);

        jbtNone4.setAlignmentY(0.9F);
        jbtNone4.setEnabled(false);
        jbtNone4.setFocusable(false);
        jbtNone4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNone4.setMargin(new java.awt.Insets(5, 25, 5, 25));
        jbtNone4.setPreferredSize(new java.awt.Dimension(130, 99));
        jbtNone4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNone4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNone4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtNone4);

        jbtNone5.setAlignmentY(0.9F);
        jbtNone5.setEnabled(false);
        jbtNone5.setFocusable(false);
        jbtNone5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNone5.setMargin(new java.awt.Insets(5, 25, 5, 25));
        jbtNone5.setPreferredSize(new java.awt.Dimension(130, 99));
        jbtNone5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNone5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNone5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtNone5);

        jbtNone6.setAlignmentY(0.9F);
        jbtNone6.setEnabled(false);
        jbtNone6.setFocusable(false);
        jbtNone6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNone6.setMargin(new java.awt.Insets(5, 25, 5, 25));
        jbtNone6.setPreferredSize(new java.awt.Dimension(130, 99));
        jbtNone6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNone6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNone6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jbtNone6);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1467, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );

        jMenu3.setText("Configurações");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(160, 35));

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setText("Selecionar Impressora");
        jMenuItem5.setPreferredSize(new java.awt.Dimension(350, 35));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem8.setText("Entrar em contato");
        jMenuItem8.setPreferredSize(new java.awt.Dimension(350, 35));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Suporte");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(140, 35));

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setText("Entrar em contato");
        jMenuItem6.setPreferredSize(new java.awt.Dimension(350, 35));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem9.setText("Licença de Uso");
        jMenuItem9.setPreferredSize(new java.awt.Dimension(350, 35));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Backup");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(170, 35));
        jMenuBar1.add(jMenu7);

        jMenu2.setText("Sair");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(70, 35));

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setText("Sair do Sistema");
        jMenuItem7.setPreferredSize(new java.awt.Dimension(350, 35));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1467, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onShow(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_onShow
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_onShow

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FSelecionarImpressora box = new FSelecionarImpressora();
        box.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        //Pandora.msgInfo("Precisa um sistema profissional? Fale conosco:\nFone/Whats: (44) 9 9876 5432");
        FSobre f = new FSobre();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jbtCadEmpresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadEmpresa1ActionPerformed
        boolean inCadFeito = false;
        try {
            Pessoa empresa = SPessoa.retrievePessoa(1l);
            if (empresa.getId().doubleValue() == 1) {
                inCadFeito = true;
                //Pandora.msgInfo("Você já cadastrou a sua empresa!\nPara alterar, acesse a aba de Consulta nesta tela!");
            }
        } catch (Exception e) {

        }

        FPessoa.getNewInstanceEmpresa(inCadFeito).setVisible(true);
        FPessoa.getInstance().addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                inicia();
            }

        });
    }//GEN-LAST:event_jbtCadEmpresa1ActionPerformed

    private void jbtModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModulosActionPerformed
        FVenda box = new FVenda("modular");
        box.setVisible(true);

//        FContas box = new FContas("Contas a Receber");
//        box.setVisible(true);
    }//GEN-LAST:event_jbtModulosActionPerformed

    private void jbtNone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtNone2ActionPerformed

    private void jbtNone3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNone3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtNone3ActionPerformed

    private void jbtNone4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNone4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtNone4ActionPerformed

    private void jbtNone5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNone5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtNone5ActionPerformed

    private void jbtNone6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNone6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtNone6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FSobre f = new FSobre();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FSobre f = new FSobre();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    
                    //UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel"); //Escuro
                    //UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
               //UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FBackground5.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FBackground5.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FBackground5.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FBackground5.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FBackground5("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtCadEmpresa1;
    private javax.swing.JButton jbtModulos;
    private javax.swing.JButton jbtNone2;
    private javax.swing.JButton jbtNone3;
    private javax.swing.JButton jbtNone4;
    private javax.swing.JButton jbtNone5;
    private javax.swing.JButton jbtNone6;
    // End of variables declaration//GEN-END:variables

    private void inicia() {
        boolean inVenda = true;
        boolean inOS = true;
        boolean inOrcamento = true;
        
        
        //Verifica se diretórios existem
        File file = new File(Configuracoes.CAMINHO_DADOS);
        if (!file.exists()) {
            file.mkdirs();
        }
        
        if (true){
            try {
                ArquivoConfig aconf = SArquivoConfig.buscaArquivo();
                Configuracoes.BD_SERVIDOR = aconf.isInServer();
                SArquivoConfig.gravaArquivo(aconf);
            } catch (Exception e) {
                Configuracoes.BD_SERVIDOR = false;
            }
        }
        
        try {
            ArquivoConfig aconf = SArquivoConfig.buscaArquivo();
            Configuracoes.IMPRESSORA = aconf.getNmImpressora();
            Configuracoes.IMPRESSORA_TAM = aconf.getDsBobina();
        } catch (Exception e) {
                
        }
        
        
        try {
            ArquivoConfig c = new ArquivoConfig();
            c = SArquivoConfig.buscaArquivo();
            Configuracoes.reportCor1 = c.getCor1();
            Configuracoes.reportCor2 = c.getCor2();
            Configuracoes.versaoArquivo = c.getVersionId();
        } catch (Exception e) {
            
        }
        
        
        boolean inCadFeito = false;
        try {
            Pessoa empresa = SPessoa.retrievePessoa(1l);
            if (empresa.getId().doubleValue() == 1){
                inCadFeito = true;
            }
        } catch (Exception e) {
            
        }
        
        
        boolean inPossuiGrupo = false;
        try {
        } catch (Exception e) {
            
        }
        
        jToolBar1.setLayout(new GridLayout(1,15,10,0));
        if (!inCadFeito){
            jbtModulos.setEnabled(false);
            
            
            jMenu1.setEnabled(false);
            
            
        } else {
            jbtModulos.setEnabled(true);
            
            jMenu1.setEnabled(true);
        }
        
        
        if (!inOrcamento){
        }
        
        if (!inOS){
        }
        
        if (!inVenda){
        }
        
        //Pandora.msgAlerta("Servidor: " + Configuracoes.BD_SERVIDOR);
      
        //jbtNone.setVisible(false);
//        jToolBar1.add(jbtNone);
//        jToolBar1.add(jbtNone);
//        jToolBar1.add(jbtNone);
//        jToolBar1.add(jbtNone);
//        jToolBar1.add(jbtNone);
        //jToolBar1.setVisible(false);
        
        String tpSys = Configuracoes.SKU.substring(2,3);
        if (tpSys.equals("B") || tpSys.equals("L")){
            if (tpSys.equals("B")){
            }
        }
        //jbtNone.setEnabled(false);
        
        
        if (Configuracoes.PRODUTOS_IN_CONT_ETQ){

        } else {

        }
    }
    
    
    private void hoverInput(KGradientPanel painel, String dsCor){
        if (dsCor.equals("blue")){
            painel.setkStartColor(new Color(0,102,255));
            painel.setkEndColor(new Color(0,102,255));
        } else if (dsCor.equals("green")){
            painel.setkStartColor(new Color(0,153,51));
            painel.setkEndColor(new Color(0,153,51));
            
        }
        painel.repaint();
    }
    
    private void hoverOutput(KGradientPanel painel, String dsCor){
        if (dsCor.equals("blue")){
            painel.setkStartColor(new Color(0,102,255));
            painel.setkEndColor(new Color(0,0,153));
        } else if (dsCor.equals("green")){
            painel.setkStartColor(new Color(0,153,51));
            painel.setkEndColor(new Color(51,255,0));
        }
        painel.repaint();
        //repaint();
    }
}
