/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualix.orcamento.visao;

import br.com.qualix.aaaFerramentas.Pandora;
import br.com.qualix.pessoa.modelo.Pessoa;
import br.com.qualix.pessoa.visao.FBoxPessoa;
import br.com.qualix.pessoa.visao.FPessoa;
import br.com.qualix.proserv.modelo.Pedido;
import br.com.qualix.proserv.modelo.PedidoPagamento;
import br.com.qualix.proserv.modelo.PedidoProduto;
import br.com.qualix.proserv.servico.SPedido;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wagner
 */
public class FIPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form FIPedido
     */
    private static String tipo_pedido = "";
    
    public FIPedido(String tipoPedido) {
        initComponents();
        tipo_pedido = tipoPedido;
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, 10);
        
        
        //Tema escuro
        //KStartColor [51,51,51]
        //KEndColor [153,153,153]
        
        //Tema azul
        //KStartColor [1,91,167]
        //KEndColor [1,135,208]
        //KEndColor [51,204,255] (mais claro)
        
        //Tema laranja
        //KStartColor [255,204,0]
        //KEndColor [255,102,0]
        
        iniciaTela();
    }
    
    public void focusCodBarras(){
        jNumberLetterField2.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcdCliente = new EditFiled.JNumberLetterField();
        jnmCliente = new EditFiled.JNumberLetterField();
        jnrTelefone = new EditFiled.JNumberLetterField();
        jbrNovoPessoa = new javax.swing.JButton();
        jbtLimpaPessoa = new javax.swing.JButton();
        jbtBuscaPessoa = new javax.swing.JButton();
        jnf = new JNumberField.JNumberField();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        jqtItem = new EditFiled.JNumberLetterField();
        kGradientPanel8 = new keeptoo.KGradientPanel();
        jvlTotal = new JNumberField.JNumberField();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jNumberLetterField1 = new EditFiled.JNumberLetterField();
        jLabel2 = new javax.swing.JLabel();
        jNumberLetterField2 = new EditFiled.JNumberLetterField();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("ATENDIMENTO AO CLIENTE");

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(1, 135, 208));
        kGradientPanel1.setkStartColor(new java.awt.Color(1, 91, 167));

        kGradientPanel2.setkBorderRadius(70);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkGradientFocus(400);
        kGradientPanel2.setkStartColor(new java.awt.Color(235, 232, 232));
        kGradientPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAIXA LIVRE");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        kGradientPanel3.setkBorderRadius(40);
        kGradientPanel3.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setkStartColor(new java.awt.Color(235, 232, 232));
        kGradientPanel3.setOpaque(false);

        jPanel4.setBackground(new java.awt.Color(230, 230, 230));
        jPanel4.setOpaque(false);

        jLabel3.setText("Cliente");

        jcdCliente.setText("jNumberLetterField1");
        jcdCliente.setTamanhoMax(8);

        jnmCliente.setEditable(false);
        jnmCliente.setText("jNumberLetterField2");
        jnmCliente.setTamanhoMax(50);
        jnmCliente.setUppercase(true);

        jnrTelefone.setEditable(false);
        jnrTelefone.setText("jNumberLetterField3");
        jnrTelefone.setTamanhoMax(20);

        jbrNovoPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/addPessoa16.png"))); // NOI18N
        jbrNovoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrNovoPessoaActionPerformed(evt);
            }
        });

        jbtLimpaPessoa.setText("Limpar");
        jbtLimpaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimpaPessoaActionPerformed(evt);
            }
        });

        jbtBuscaPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/lupa16.png"))); // NOI18N
        jbtBuscaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscaPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtBuscaPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbrNovoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtLimpaPessoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jnmCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jnrTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jnf, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtBuscaPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jnmCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jnrTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtLimpaPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbrNovoPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel4.setkBorderRadius(70);
        kGradientPanel4.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel4.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel4.setOpaque(false);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTableProduto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 3"
            }
        ));
        jTableProduto.setGridColor(new java.awt.Color(255, 255, 255));
        jTableProduto.setOpaque(false);
        jTableProduto.setRowHeight(25);
        jTableProduto.getTableHeader().setReorderingAllowed(false);
        jTableProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduto);
        if (jTableProduto.getColumnModel().getColumnCount() > 0) {
            jTableProduto.getColumnModel().getColumn(0).setPreferredWidth(57);
            jTableProduto.getColumnModel().getColumn(1).setPreferredWidth(450);
            jTableProduto.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTableProduto.getColumnModel().getColumn(3).setPreferredWidth(130);
        }

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setOpaque(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/salvar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/limpar32.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        kGradientPanel6.setkBorderRadius(60);
        kGradientPanel6.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel6.setkStartColor(new java.awt.Color(235, 232, 232));
        kGradientPanel6.setOpaque(false);

        jqtItem.setBorder(null);
        jqtItem.setText("jNumberLetterField3");
        jqtItem.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jqtItem.setOpaque(false);
        jqtItem.setTamanhoMax(5);
        jqtItem.setUppercase(true);

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jqtItem, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jqtItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        kGradientPanel8.setkBorderRadius(60);
        kGradientPanel8.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel8.setkStartColor(new java.awt.Color(235, 232, 232));
        kGradientPanel8.setOpaque(false);

        jvlTotal.setBorder(null);
        jvlTotal.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jvlTotal.setOpaque(false);

        javax.swing.GroupLayout kGradientPanel8Layout = new javax.swing.GroupLayout(kGradientPanel8);
        kGradientPanel8.setLayout(kGradientPanel8Layout);
        kGradientPanel8Layout.setHorizontalGroup(
            kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jvlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel8Layout.setVerticalGroup(
            kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jvlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kGradientPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kGradientPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kGradientPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                .addContainerGap())
        );

        kGradientPanel5.setkBorderRadius(40);
        kGradientPanel5.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel5.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel5.setOpaque(false);

        jNumberLetterField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jNumberLetterField1.setText("1");
        jNumberLetterField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jNumberLetterField1.setNumber(true);
        jNumberLetterField1.setOpaque(false);
        jNumberLetterField1.setTamanhoMax(4);
        jNumberLetterField1.setUppercase(true);
        jNumberLetterField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumberLetterField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("x");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jNumberLetterField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jNumberLetterField2.setOpaque(false);
        jNumberLetterField2.setTamanhoMax(50);
        jNumberLetterField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumberLetterField2KeyPressed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/barras_105_49.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNumberLetterField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNumberLetterField2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNumberLetterField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jNumberLetterField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1520, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kGradientPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                            .addComponent(kGradientPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBuscaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscaPessoaActionPerformed
        FBoxPessoa.getNewInstance().setVisible(true);
        FBoxPessoa.getInstance().addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                Pessoa pessoa = FBoxPessoa.getPessoaSelecionada();
                if (pessoa != null){
                    jcdCliente.setText(pessoa.getId()+"");
                    jnmCliente.setText(pessoa.getNmPessoa());
                    jnrTelefone.setText(pessoa.getNrTelefone1());
                    FBoxPessoa.removePessoaSelecionada();
                }
            }

        });
    }//GEN-LAST:event_jbtBuscaPessoaActionPerformed

    private void jbtLimpaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimpaPessoaActionPerformed
        jcdCliente.setText("");
        jnmCliente.setText("CLIENTE NÃO IDENTIFICADO");
        jnrTelefone.setText("");
    }//GEN-LAST:event_jbtLimpaPessoaActionPerformed

    private void jbrNovoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrNovoPessoaActionPerformed
        FPessoa.getNewInstanceAutoCadastro().setVisible(true);
        FPessoa.getInstance().addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                Pessoa pessoa = FPessoa.getPessoaSelecionada();
                if (pessoa != null){
                    jcdCliente.setText(pessoa.getId()+"");
                    jnmCliente.setText(pessoa.getNmPessoa());
                    jnrTelefone.setText(pessoa.getNrTelefone1());
                } else {
                    jcdCliente.setText("");
                    jnmCliente.setText("");
                    jnrTelefone.setText("");

                }
            }

        });
    }//GEN-LAST:event_jbrNovoPessoaActionPerformed

    private void jNumberLetterField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumberLetterField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumberLetterField1ActionPerformed

    private void jNumberLetterField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumberLetterField2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            DefaultTableModel dm = (DefaultTableModel) jTableProduto.getModel();
            dm.setRowCount(dm.getRowCount()+1);
            
            dm.setValueAt("  1x", dm.getRowCount()-1, 0);
            //dm.setValueAt(209, dm.getRowCount()-1, 0);
            dm.setValueAt("PRODUTO ESPECIAL PARA COMPRADOR IMPORTANTE", dm.getRowCount()-1, 1);
            dm.setValueAt("", dm.getRowCount()-1, 2);
            dm.setValueAt("R$ 1.290,30", dm.getRowCount()-1, 3);
        } else if (evt.getKeyCode() == KeyEvent.VK_DELETE){
            DefaultTableModel dm = (DefaultTableModel) jTableProduto.getModel();
            if (dm.getRowCount() > 0){
                int opt = JOptionPane.showConfirmDialog(null, "Deseja excluir o último item?");
                if (opt == 0){
                    dm.removeRow(dm.getRowCount()-1);
                    jNumberLetterField2.grabFocus();
                }
                
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_F9){
            jButton1.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_F2){
            jButton2.doClick();
        }
        atualizaStatus();
    }//GEN-LAST:event_jNumberLetterField2KeyPressed

    private void jTableProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableProdutoKeyReleased
        if (jTableProduto.getSelectedRow() >= 0){
            if (evt.getKeyCode() == KeyEvent.VK_DELETE){
                int opt = JOptionPane.showConfirmDialog(null, "Deseja excluir este item?");
                if (opt == 0){
                    DefaultTableModel dm = (DefaultTableModel) jTableProduto.getModel();
                    dm.removeRow(jTableProduto.getSelectedRow());
                    jNumberLetterField2.grabFocus();
                }
            }
        }
    }//GEN-LAST:event_jTableProdutoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            
            ArrayList<PedidoProduto> listaProdutos = new ArrayList<>();
            PedidoProduto pp;
            for (int i = 0; i < jTableProduto.getRowCount(); i++) {
                pp = new PedidoProduto();
            }
            ArrayList<PedidoPagamento> listaPagamentos = new ArrayList<>();
            Pedido pedido = SPedido.gravaPedido(null, jnmCliente.getText(), tipo_pedido, "DIGITADO", LocalDateTime.now(), null, null, null, jvlTotal.getValue(), BigDecimal.ZERO, jvlTotal.getValue(), true, true, "", isClosed, listaProdutos, listaPagamentos, "", false, "");
            SPedido.imprimir(pedido);
            
            jButton2.doClick();
        } catch (Exception e) {
            Pandora.ex(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jbtLimpaPessoa.doClick();
        DefaultTableModel dm = (DefaultTableModel) jTableProduto.getModel();
        dm.setNumRows(0);
        atualizaStatus();
        jNumberLetterField2.grabFocus();
                
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private EditFiled.JNumberLetterField jNumberLetterField1;
    private EditFiled.JNumberLetterField jNumberLetterField2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JButton jbrNovoPessoa;
    private javax.swing.JButton jbtBuscaPessoa;
    private javax.swing.JButton jbtLimpaPessoa;
    private EditFiled.JNumberLetterField jcdCliente;
    private JNumberField.JNumberField jnf;
    private EditFiled.JNumberLetterField jnmCliente;
    private EditFiled.JNumberLetterField jnrTelefone;
    private EditFiled.JNumberLetterField jqtItem;
    private JNumberField.JNumberField jvlTotal;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel8;
    // End of variables declaration//GEN-END:variables

    private void iniciaTela() {
        try {
            jnf.setVisible(false);
            jNumberLetterField1.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.GRAY));
            atualizaStatus();
            
            jNumberLetterField2.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.GRAY));
            
            jbtLimpaPessoa.doClick();
            jNumberLetterField1.setText("1");
            Thread.sleep(30);
            jNumberLetterField2.grabFocus();
            
            jScrollPane1.getViewport().setBackground(Color.WHITE);
            //jTableProduto.setBackground(Color.red);
            
            jTableProduto.getColumnModel().getColumn(0).setHeaderValue("");
            jTableProduto.getColumnModel().getColumn(1).setHeaderValue("");
            jTableProduto.getColumnModel().getColumn(2).setHeaderValue("");
            jTableProduto.getColumnModel().getColumn(3).setHeaderValue("");
            jTableProduto.getTableHeader().resizeAndRepaint();
            
            
        } catch (InterruptedException ex) {
            Pandora.msgException(ex);
        }
    }
    
    private void atualizaStatus(){
        boolean inLivre = true;
        boolean inFechado = false;
        
        Font f = jLabel1.getFont();
        if (inFechado){
            jLabel1.setText("CAIXA FECHADO");
            jLabel1.setForeground(Color.BLACK);
            jLabel1.setForeground(new Color(234,0,0));
            jLabel1.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
            return;
        }
        
        if (jTableProduto.getRowCount() > 0){
            inLivre = false;
        }
        
        if (!jcdCliente.getText().equals("")){
            inLivre = false;
        }
        
        if (inLivre){
            jLabel1.setText("CAIXA LIVRE");
            jLabel1.setForeground(Color.black);
            //jLabel1.setFont(f.deriveFont(f.getStyle() | ~Font.BOLD));
            jLabel1.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
            
        } else {
            jLabel1.setText("CAIXA OCUPADO");
            jLabel1.setForeground(new Color(204,0,0));
            jLabel1.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
            
        }
    }
    
    
}
