/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualix.orcamento.visao;

import br.com.qualix.aaaConfig.Configuracoes;
import br.com.qualix.aaaFerramentas.Pandora;
import br.com.qualix.proserv.modelo.Pedido;
import br.com.qualix.proserv.servico.SPedido;

/**
 *
 * @author Wagner
 */
public class FPedidoBoxTipoPedido extends javax.swing.JDialog {

    /**
     * Creates new form FPedidoBoxSituacao
     */
    
    private static Long idPedido;
    private static String  tpPedido;
    
    public FPedidoBoxTipoPedido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        try {
            this.setIconImage(Configuracoes.LOGO_SISTEMA);
        } catch (Exception e) {
            
        }
    }
    
    public FPedidoBoxTipoPedido(java.awt.Frame parent, boolean modal, String tp_pedido, Long id) {
        super(parent, modal);
        initComponents();
        idPedido = id;
        tpPedido = tp_pedido;
        
        jLabel1.setText("Converter " + tp_pedido + " para");
        if (tp_pedido.equals("ORÇAMENTO")){
            jbtOrcamento.setEnabled(false);
        } else if (tp_pedido.equals("ORDEM DE SERVIÇO")){
            jbtOS.setEnabled(false);
        } else if (tp_pedido.equals("VENDA")){
            jbtVenda.setEnabled(false);
        } 
        
        try {
            this.setIconImage(Configuracoes.LOGO_SISTEMA);
        } catch (Exception e) {
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtOrcamento = new javax.swing.JButton();
        jbtOS = new javax.swing.JButton();
        jbtVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Altera Situação");

        jbtOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/orcamento_64.png"))); // NOI18N
        jbtOrcamento.setText("Orçamento");
        jbtOrcamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtOrcamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOrcamentoActionPerformed(evt);
            }
        });

        jbtOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/os_64_1.png"))); // NOI18N
        jbtOS.setText("Ordem de Serviço");
        jbtOS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtOS.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOSActionPerformed(evt);
            }
        });

        jbtVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/venda_64_1.png"))); // NOI18N
        jbtVenda.setText("Venda");
        jbtVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVendaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Alterar pedido para:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtOS, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtOS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOrcamentoActionPerformed
        try {
            Pedido pedido = new Pedido();
            SPedido spedido = new SPedido();
            
            pedido = spedido.retrievePedido(idPedido);
            pedido.setTpPedido("ORÇAMENTO");
            spedido.grava(pedido);
            
            Pandora.msgInfo("Tipo do Documento alterado com sucesso!");
            dispose();
        } catch (Exception e) {
            Pandora.ex(e);
        }
        
    }//GEN-LAST:event_jbtOrcamentoActionPerformed

    private void jbtOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOSActionPerformed
        try {
            
            Pedido pedido = new Pedido();
            SPedido spedido = new SPedido();
            
            pedido = spedido.retrievePedido(idPedido);
            pedido.setTpPedido("ORDEM DE SERVIÇO");
            spedido.grava(pedido);
            
            Pandora.msgInfo("Tipo do Documento alterado com sucesso!");
            dispose();
        } catch (Exception e) {
            Pandora.ex(e);
        }
    }//GEN-LAST:event_jbtOSActionPerformed

    private void jbtVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVendaActionPerformed
        try {
            
            Pedido pedido = new Pedido();
            SPedido spedido = new SPedido();
            
            pedido = spedido.retrievePedido(idPedido);
            pedido.setTpPedido("VENDA");
            spedido.grava(pedido);
            
            Pandora.msgInfo("Tipo do Documento alterado com sucesso!");
            dispose();
        } catch (Exception e) {
            Pandora.ex(e);
        }
    }//GEN-LAST:event_jbtVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPedidoBoxSituacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPedidoBoxSituacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPedidoBoxSituacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPedidoBoxSituacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FPedidoBoxSituacao dialog = new FPedidoBoxSituacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtOS;
    private javax.swing.JButton jbtOrcamento;
    private javax.swing.JButton jbtVenda;
    // End of variables declaration//GEN-END:variables
}
