/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualix.orcamento.visao;

import br.com.qualix.aaaConfig.Configuracoes;
import br.com.qualix.aaaFerramentas.Pandora;
import br.com.qualix.proserv.modelo.Pedido;
import br.com.qualix.proserv.servico.SPedido;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wagner
 */
public class FRelatorioVendas extends javax.swing.JFrame {

    /**
     * Creates new form FRelatorioVendas
     */
    
    private static String tp_abertura = "";
    
    public FRelatorioVendas(String tpAbertura) {
        tp_abertura = tpAbertura;
        initComponents();
        jnf.setVisible(false);
        
        try {
            this.setIconImage(Configuracoes.LOGO_SISTEMA);
        } catch (Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jdtIniPes = new EditFiled.JNumberLetterField();
        jLabel13 = new javax.swing.JLabel();
        jdtFimPes = new EditFiled.JNumberLetterField();
        jBtConsulta = new javax.swing.JButton();
        jnf = new JNumberField.JNumberField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Início:");

        jdtIniPes.setText("jNumberLetterField1");
        jdtIniPes.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jdtIniPes.setTamanhoMax(10);
        jdtIniPes.setUppercase(true);
        jdtIniPes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdtIniPesFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("Fim:");

        jdtFimPes.setText("jNumberLetterField1");
        jdtFimPes.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jdtFimPes.setTamanhoMax(10);
        jdtFimPes.setUppercase(true);
        jdtFimPes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdtFimPesFocusLost(evt);
            }
        });

        jBtConsulta.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jBtConsulta.setText("Pesquisa");
        jBtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConsultaActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Digitado", "Efetivado", "Cancelado"
            }
        ));
        jTable2.setRowHeight(30);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdtIniPes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdtFimPes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(367, 367, 367)
                        .addComponent(jnf, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jBtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdtIniPes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jdtFimPes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jdtIniPesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdtIniPesFocusLost
        try {
            jdtIniPes.setText(Pandora.validaData(jdtIniPes.getText()));
        } catch (Exception e) {
            jdtIniPes.setText("");
            jdtIniPes.grabFocus();
            Pandora.ex(e);
        }
    }//GEN-LAST:event_jdtIniPesFocusLost

    private void jdtFimPesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdtFimPesFocusLost
        try {
            jdtFimPes.setText(Pandora.validaData(jdtFimPes.getText()));
        } catch (Exception e) {
            jdtFimPes.setText("");
            jdtFimPes.grabFocus();
            Pandora.ex(e);
        }
    }//GEN-LAST:event_jdtFimPesFocusLost

    private void jBtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConsultaActionPerformed
        try {
            LocalDateTime ini = null;
            if (!jdtIniPes.getText().equals("")){
                ini = LocalDateTime.of(Pandora.STR_LD(jdtIniPes.getText()), LocalTime.of(0, 0));
            }
            LocalDateTime fim = null;
            if (!jdtFimPes.getText().equals("")){
                fim = LocalDateTime.of(Pandora.STR_LD(jdtFimPes.getText()), LocalTime.of(23, 59, 59));
            }

            ArrayList<Pedido> lista = SPedido.retrievePedido();

            //Ordenação aqui

            DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
            dm.setNumRows(0);

            BigDecimal vlDigitado  = BigDecimal.ZERO;
            BigDecimal vlEfetivado = BigDecimal.ZERO;
            BigDecimal vlCancelado = BigDecimal.ZERO;
            
            boolean inMostra;
            for (Pedido pedido : lista) {
                inMostra = true;
                if (fim != null && pedido.getDtTransacao().isAfter(fim)){
                    inMostra = false;
                }
                if (ini != null && pedido.getDtTransacao().isBefore(ini)){
                    inMostra = false;
                }
                if (!pedido.getTpPedido().equals("")  && !pedido.getTpPedido().equals(tp_abertura)){
                    inMostra = false;
                }

                if (inMostra){
                    if (pedido.getTpSituacao().equals("DIGITADO")){
                        vlDigitado = vlDigitado.add(pedido.getVlTotal());
                    } else if (pedido.getTpSituacao().equals("EFETIVADO")){
                        vlEfetivado = vlEfetivado.add(pedido.getVlTotal());
                    } else if (pedido.getTpSituacao().equals("CANCELADO")){
                        vlCancelado = vlCancelado.add(pedido.getVlTotal());
                    }
                }
            }
            
            
            dm.setNumRows(dm.getRowCount()+1);
            dm.setValueAt(tp_abertura, dm.getRowCount()-1, 0);
            jnf.setValue(vlDigitado);
            dm.setValueAt(jnf.getText(), dm.getRowCount()-1, 1);
            
            jnf.setValue(vlEfetivado);
            dm.setValueAt(jnf.getText(), dm.getRowCount()-1, 2);
            
            jnf.setValue(vlCancelado);
            dm.setValueAt(jnf.getText(), dm.getRowCount()-1, 3);
            
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jBtConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRelatorioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRelatorioVendas("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtConsulta;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private EditFiled.JNumberLetterField jdtFimPes;
    private EditFiled.JNumberLetterField jdtIniPes;
    private JNumberField.JNumberField jnf;
    // End of variables declaration//GEN-END:variables
}
