/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualix.orcamento.visao;

import br.com.qualix.proserv.modelo.Pedido;
import br.com.qualix.proserv.modelo.PedidoPagamento;
import java.math.BigDecimal;
import java.util.ArrayList;

/**
 *
 * @author Wagner
 */
public class FTipoImpressaoPedido extends javax.swing.JFrame {

    /**
     * Creates new form FTipoImpressaoPedido
     */
    private static FTipoImpressaoPedido INSTANCE = null;
    private static ArrayList<Pedido> lista_pedido = new ArrayList<>();
    public FTipoImpressaoPedido() {
        initComponents();
        
    }
    
    public static FTipoImpressaoPedido getNewInstance(ArrayList<Pedido> listaPedido){
        lista_pedido = listaPedido;
        INSTANCE = new FTipoImpressaoPedido();
        return INSTANCE;
    }
    
    public static FTipoImpressaoPedido getInstance(ArrayList<Pedido> listaPedido){
        lista_pedido = listaPedido;
        if (INSTANCE == null){
            INSTANCE = new FTipoImpressaoPedido();
        }
        return INSTANCE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Tipo de Impressão");

        jButton1.setText("Pagamentos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(503, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        boolean inEncontrou = false;
        ArrayList<PedidoPagamento> listaPagamento = new ArrayList<>();
        BigDecimal vendas = BigDecimal.ZERO;
        for (Pedido pedido : lista_pedido) {
            vendas = vendas.add(pedido.getVlTotal());
            for (PedidoPagamento pag : pedido.getListaPagamento()) {
                inEncontrou = false;
                
                for (PedidoPagamento pedidoPagamento : listaPagamento) {
                    if (pag.getPagamento().getId() == pedidoPagamento.getPagamento().getId()){
                        inEncontrou = true;
                        pedidoPagamento.setVlPagamento(pedidoPagamento.getVlPagamento().add(pag.getVlPagamento()));
                    }
                }
                if (!inEncontrou){
                    listaPagamento.add(pag);
                }
            }
        }
        
        System.out.println("Inicio");
        for (PedidoPagamento pedidoPagamento : listaPagamento) {
            System.out.println(pedidoPagamento.getPagamento().getDsTipoPagamento() + " " + pedidoPagamento.getVlPagamento());
        }
        System.out.println("VENDAS: " + vendas);
        System.out.println("Fim");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTipoImpressaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTipoImpressaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTipoImpressaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTipoImpressaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTipoImpressaoPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
