/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualix.aaaConfig.visao;

import br.com.qualix.aaaConfig.Configuracoes;
import br.com.qualix.aaaConfig.modelo.ArquivoConfig;
import br.com.qualix.aaaConfig.servico.SArquivoConfig;
import br.com.qualix.aaaFerramentas.IntegerToHexa;
import br.com.qualix.aaaFerramentas.Pandora;
import com.google.gson.Gson;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.nio.channels.FileChannel;
import java.time.LocalDateTime;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Wagner
 */
public class FConfiguracoes extends javax.swing.JFrame {

    /**
     * Creates new form FConfiguracoes
     */
    public FConfiguracoes() {
        initComponents();
        
        iniciaTela();
        
        try {
            this.setIconImage(Configuracoes.LOGO_SISTEMA);
        } catch (Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelCor1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelCor2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jdsCor1 = new EditFiled.JNumberLetterField();
        jdsCor2 = new EditFiled.JNumberLetterField();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações do Sistema");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cores do Relatório");

        jLabel2.setText("Cor 1");

        jPanelCor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCor1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCor1Layout = new javax.swing.GroupLayout(jPanelCor1);
        jPanelCor1.setLayout(jPanelCor1Layout);
        jPanelCor1Layout.setHorizontalGroup(
            jPanelCor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanelCor1Layout.setVerticalGroup(
            jPanelCor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/palete1_24.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/palete1_24.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanelCor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelCor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCor2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelCor2Layout = new javax.swing.GroupLayout(jPanelCor2);
        jPanelCor2.setLayout(jPanelCor2Layout);
        jPanelCor2Layout.setHorizontalGroup(
            jPanelCor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanelCor2Layout.setVerticalGroup(
            jPanelCor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setText("Cor 2");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jdsCor1.setText("jNumberLetterField1");
        jdsCor1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jdsCor1.setTamanhoMax(7);
        jdsCor1.setUppercase(true);
        jdsCor1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdsCor1FocusLost(evt);
            }
        });
        jdsCor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jdsCor1KeyReleased(evt);
            }
        });

        jdsCor2.setText("jNumberLetterField2");
        jdsCor2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jdsCor2.setTamanhoMax(7);
        jdsCor2.setUppercase(true);
        jdsCor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jdsCor2KeyReleased(evt);
            }
        });

        jButton4.setText("Configuração Original");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdsCor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdsCor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelCor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelCor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdsCor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdsCor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel4.setBackground(new java.awt.Color(230, 230, 230));
        jLabel4.setOpaque(true);

        jLabel5.setText("Escolher Logotipo do Relatório");

        jButton5.setText("Escolher Logotipo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Configuração Original");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addContainerGap(81, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cores do Relatório / Logotipo", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FColor box = new FColor();
        box.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                if (!FColor.getCor().equals("")){
                    jdsCor1.setText(FColor.getCor());
                    Color cor;
                    cor = IntegerToHexa.rgbCodeToColor(jdsCor1.getText());
                    if (cor == null){
                        cor = new Color(255,255,255);
                    }
                    jPanelCor1.setBackground(cor);
                }
            }
            
        });
        
        box.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jdsCor1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdsCor1FocusLost
        
    }//GEN-LAST:event_jdsCor1FocusLost

    private void jdsCor1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdsCor1KeyReleased
        Color cor;
        cor = IntegerToHexa.rgbCodeToColor(jdsCor1.getText());
        if (cor == null){
            cor = new Color(255,255,255);
        }
        jPanelCor1.setBackground(cor);
    }//GEN-LAST:event_jdsCor1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FColor box = new FColor();
        box.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                if (!FColor.getCor().equals("")){
                    jdsCor2.setText(FColor.getCor());
                    Color cor;
                    cor = IntegerToHexa.rgbCodeToColor(jdsCor2.getText());
                    if (cor == null){
                        cor = new Color(255,255,255);
                    }
                    jPanelCor2.setBackground(cor);
                }
            }
            
        });
        
        box.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jdsCor2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdsCor2KeyReleased
        Color cor;
        cor = IntegerToHexa.rgbCodeToColor(jdsCor2.getText());
        if (cor == null){
            cor = new Color(255,255,255);
        }
        jPanelCor2.setBackground(cor);
    }//GEN-LAST:event_jdsCor2KeyReleased

    private void jPanelCor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCor1MouseClicked
        if (evt.getClickCount() == 2){
            jButton1.doClick();
        }
    }//GEN-LAST:event_jPanelCor1MouseClicked

    private void jPanelCor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCor2MouseClicked
        if (evt.getClickCount() == 2){
            jButton2.doClick();
        }
    }//GEN-LAST:event_jPanelCor2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Color cor;
            cor = IntegerToHexa.rgbCodeToColor(jdsCor1.getText());
            if (cor == null){
                throw new Exception("Erro");
            }
            Configuracoes.reportCor1 = jdsCor1.getText();
            
            
            cor = IntegerToHexa.rgbCodeToColor(jdsCor2.getText());
            if (cor == null){
                throw new Exception("Erro");
            }
            Configuracoes.reportCor2 = jdsCor2.getText();

            ArquivoConfig c = new ArquivoConfig();
            c = SArquivoConfig.buscaArquivo();
            c.setCor1(Configuracoes.reportCor1);
            c.setCor2(Configuracoes.reportCor2);
            SArquivoConfig.gravaArquivo(c);
            
            
            
        } catch (Exception e) {
            
        }
        
        dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Configuracoes.reportCor1 = "";
            Configuracoes.reportCor2 = "";
            ArquivoConfig c = new ArquivoConfig();
            c = SArquivoConfig.buscaArquivo();
            c.setCor1(Configuracoes.reportCor1);
            c.setCor2(Configuracoes.reportCor2);
            SArquivoConfig.gravaArquivo(c);
            
        } catch (Exception e) {
            
        }
        
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            
            String dataa = LocalDateTime.now().getYear() + "-" + LocalDateTime.now().getMonthValue() + "-" + LocalDateTime.now().getDayOfMonth();
            
            JFileChooser fc = new JFileChooser();
            fc.setDialogType(javax.swing.JFileChooser.FILES_ONLY);
            fc.setApproveButtonText("Abrir");
            fc.setFileFilter(new FileNameExtensionFilter("Arquivos *.png", "png"));
            //fc.setCurrentDirectory(new java.io.File("C:\\Qualix\\sistema"));
            //fc.setSelectedFile(new java.io.File("C:\\Qualix\\sistema\\backupSistemaQualix_"+dataa+".zip"));
            fc.setToolTipText("");
            if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
                
                    //tentativa 1
//                    BufferedReader br;
//                    try {
//                        br = new BufferedReader(new InputStreamReader(new FileInputStream(fc.getSelectedFile().getPath()), "Windows-1252"));
//                        String linha = "";
//                        while (br.ready()) {
//                            linha = br.readLine();
//                        }
//                        //arq = gson.fromJson(linha, ArquivoConfig.class);
//                        br.close();
//                        
//                        BufferedWriter bw;
//                        bw = new BufferedWriter(new FileWriter(Configuracoes.CAMINHO_DADOS+"\\wow.png"));
//                        bw.append(linha);
//                        bw.close();
//                        
//                    } catch (Exception ex) {
//                        Pandora.msgException(ex);
//                    }
                   //fim tenta 1 
                    File busca   = new File(fc.getSelectedFile().getPath());
                    File destino = new File(Configuracoes.CAMINHO_DADOS+"\\logo.png");
                   
                    if (destino.exists()){
                        destino.delete();
                    }

                    FileChannel sourceChannel = null;
                    FileChannel destinationChannel = null;

                    try {
                        sourceChannel = new FileInputStream(busca).getChannel();
                        destinationChannel = new FileOutputStream(destino).getChannel();
                        sourceChannel.transferTo(0, sourceChannel.size(), destinationChannel);
                    } finally {
                        if (sourceChannel != null && sourceChannel.isOpen()){
                            sourceChannel.close();
                        }
                        if (destinationChannel != null && destinationChannel.isOpen()){
                            destinationChannel.close();
                        }
                   }

                    //Imagem original
                    //jLabel4.setIcon(new javax.swing.ImageIcon(fc.getSelectedFile().getPath()));
                    
                    Image image = null;
                    File sourceimage = new File("C:/Qualix/sistema/small/logo.png");
                    image = ImageIO.read(sourceimage);
                    
                    
                    //Imagem com tamanho predefinido
                    //jLabel4.setIcon(new ImageIcon(image.getScaledInstance(475, 130, Image.SCALE_DEFAULT)));
                    
                    
                    //ImageIcon ii = new ImageIcon(image);
                    //jLabel4.setIcon(new ImageIcon(image.getScaledInstance(ii.getIconHeight()/3, ii.getIconWidth()/3, Image.SCALE_DEFAULT)));
                    
                    
                    ImageIcon ii = new ImageIcon(image);
                    double larguraLogo = ii.getIconWidth();
                    double alturaLogo = ii.getIconHeight();
                    double result = (alturaLogo / larguraLogo) * 100;
                    boolean pelaLargura = true;
                    if (result > 27){
                        pelaLargura = false;
                    }
                    double propL = 0;
                    double propA = 0;
                    double propL2 = 0;
                    double propA2 = 0;
                    if (pelaLargura){
                        propL = 475 / larguraLogo;
                        propL2 = larguraLogo * propL;
                        propA2 = alturaLogo * propL;
                        
                    } else {
                        propA = 130 / alturaLogo;
                        propA2 = alturaLogo * propA;
                        propL2 = larguraLogo * propA;
                    }
                    int a = (int) propA2;
                    int l = (int) propL2;
                    jLabel4.setIcon(new ImageIcon(image.getScaledInstance(a, l, Image.SCALE_DEFAULT)));
                    
                    
                    Pandora.msgAlerta("Logotipo salva com Sucesso!");

                    
//                    dispose();
            } else {
                Pandora.msgAlerta("Cancelado!");
            }
            
            
                
            
        } catch (Exception e) {
            Pandora.msgErro("Erro ao selecionar arquivo!");
            dispose();
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        File destino = new File(Configuracoes.CAMINHO_DADOS+"\\logo.png");
        if (destino.exists()){
            destino.delete();
        }
        Pandora.msgInfo("Restaurado com sucesso!");
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FConfiguracoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCor1;
    private javax.swing.JPanel jPanelCor2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private EditFiled.JNumberLetterField jdsCor1;
    private EditFiled.JNumberLetterField jdsCor2;
    // End of variables declaration//GEN-END:variables

    private void iniciaTela() {
        jPanel3.setVisible(false);
        
        jdsCor1.setText(Configuracoes.reportCor1);
        Color cor;
        cor = IntegerToHexa.rgbCodeToColor(jdsCor1.getText());
        if (cor == null){
            cor = new Color(255,255,255);
        }
        jPanelCor1.setBackground(cor);
        
        
        jdsCor2.setText(Configuracoes.reportCor2);
        cor = IntegerToHexa.rgbCodeToColor(jdsCor2.getText());
        if (cor == null){
            cor = new Color(255,255,255);
        }
        jPanelCor2.setBackground(cor);
    }
}
