/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualix.financeiro.visao;

import br.com.qualix.aaaFerramentas.Pandora;
import br.com.qualix.financeiro.modelo.Conta;
import br.com.qualix.financeiro.servico.SConta;
import java.math.BigDecimal;
import java.math.MathContext;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wagner
 */
public class FDigitarConta extends javax.swing.JFrame {

    /**
     * Creates new form FDigitarConta
     */
    
    private ArrayList<Conta> contasGerar = new ArrayList<>();
    
    public FDigitarConta() {
        initComponents();
        
        try {
            iniciaTela();
        } catch (Exception e) {
            Pandora.ex(e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jNumberLetterField1 = new EditFiled.JNumberLetterField();
        jLabel2 = new javax.swing.JLabel();
        jdtDigitacao = new EditFiled.JNumberLetterField();
        jLabel3 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jvlTotal = new JNumberField.JNumberField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jdtPrimeiroVenc = new EditFiled.JNumberLetterField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jdsObs = new EditFiled.JNumberLetterField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jtpClassificacao = new javax.swing.JComboBox<>();
        jlbClassificacao = new javax.swing.JLabel();
        jnf = new JNumberField.JNumberField();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jqtParcelas = new EditFiled.JNumberLetterField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Digitação de Conta");

        jLabel1.setText("Tipo de Movimento");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Entrada", "Saída" }));

        jNumberLetterField1.setText("jNumberLetterField1");
        jNumberLetterField1.setTamanhoMax(5);

        jLabel2.setText("Cliente");

        jdtDigitacao.setText("jNumberLetterField2");
        jdtDigitacao.setTamanhoMax(10);
        jdtDigitacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdtDigitacaoFocusLost(evt);
            }
        });

        jLabel3.setText("Data Digitação");

        kGradientPanel1.setkEndColor(new java.awt.Color(119, 119, 235));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 204, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Preenchimento Rápido - Vencimento:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor");

        jvlTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jvlTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jvlTotalKeyReleased(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data da Digitação", "7 Dias", "10 Dias", "15 Dias", "30 Dias", "30/60 dias", "30/60/90 dias", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jdtPrimeiroVenc.setText("jNumberLetterField3");
        jdtPrimeiroVenc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jdtPrimeiroVenc.setTamanhoMax(10);
        jdtPrimeiroVenc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdtPrimeiroVencFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Primeiro Vencimento");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Observações");

        jdsObs.setText("jNumberLetterField4");
        jdsObs.setTamanhoMax(200);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 254, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdtPrimeiroVenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jvlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jdsObs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdtPrimeiroVenc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jvlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jComboBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdsObs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parcela", "Vencimento", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Parcelas a serem geradas");
        jLabel8.setOpaque(true);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/salvar.png"))); // NOI18N
        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rem24.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jtpClassificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlbClassificacao.setText("Classificação");

        kGradientPanel4.setkBorderRadius(25);
        kGradientPanel4.setkEndColor(new java.awt.Color(193, 193, 193));
        kGradientPanel4.setkStartColor(new java.awt.Color(240, 240, 240));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Parcelas");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minus20.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add24.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jqtParcelas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jqtParcelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jqtParcelas.setNumber(true);
        jqtParcelas.setTamanhoMax(3);
        jqtParcelas.setUppercase(true);
        jqtParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jqtParcelasKeyReleased(evt);
            }
        });

        jCheckBox1.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox1.setText("Esta conta já está paga");
        jCheckBox1.setOpaque(false);

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox1)
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jqtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel4Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jqtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNumberLetterField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbClassificacao)
                            .addComponent(jtpClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdtDigitacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jlbClassificacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNumberLetterField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdtDigitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtpClassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jnf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            SConta.gravaContas(contasGerar);
            Pandora.msgInfo("Conta gerada com sucesso!");
        } catch (Exception e) {
            Pandora.ex(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jvlTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jvlTotalKeyReleased
        calculaParcelas();
    }//GEN-LAST:event_jvlTotalKeyReleased

    private void jqtParcelasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jqtParcelasKeyReleased
        calculaParcelas();
    }//GEN-LAST:event_jqtParcelasKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int qt = Integer.parseInt(jqtParcelas.getText());
        qt++;
        jqtParcelas.setText(qt+"");
        calculaParcelas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int qt = Integer.parseInt(jqtParcelas.getText());
        if (qt>1){
            qt--;
        }
        jqtParcelas.setText(qt+"");
        calculaParcelas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jdtPrimeiroVencFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdtPrimeiroVencFocusLost
        
        
        
        calculaParcelas();
    }//GEN-LAST:event_jdtPrimeiroVencFocusLost

    private void jdtDigitacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdtDigitacaoFocusLost
        
        
        
        calculaParcelas();
    }//GEN-LAST:event_jdtDigitacaoFocusLost

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        try {
            int option = jComboBox2.getSelectedIndex();
            LocalDate dataDig = Pandora.STR_LD(jdtDigitacao.getText());
            LocalDate dataVenc = LocalDate.now();

            if (option == 0){
                dataVenc = dataDig;
                jqtParcelas.setText("1");
            } else if (option == 1){ //7
                dataVenc = dataDig.plusDays(7);
                jqtParcelas.setText("1");
            } else if (option == 2){ //10
                dataVenc = dataDig.plusDays(10);
                jqtParcelas.setText("1");
            } else if (option == 3){ //15
                dataVenc = dataDig.plusDays(15);
                jqtParcelas.setText("1");
            } else if (option == 4){ //30
                dataVenc = dataDig.plusDays(30);
                jqtParcelas.setText("1");
            } else if (option == 5){ //30/60
                dataVenc = dataDig.plusDays(30);
                jqtParcelas.setText("2");
            } else if (option == 6){ //30/60/90
                dataVenc = dataDig.plusDays(30);
                jqtParcelas.setText("3");
            }
        
            jdtPrimeiroVenc.setText(Pandora.LD_STR(dataVenc));
            calculaParcelas();
        } catch (Exception ex) {
            Pandora.msgException(ex);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDigitarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDigitarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDigitarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDigitarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDigitarConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private EditFiled.JNumberLetterField jNumberLetterField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private EditFiled.JNumberLetterField jdsObs;
    private EditFiled.JNumberLetterField jdtDigitacao;
    private EditFiled.JNumberLetterField jdtPrimeiroVenc;
    private javax.swing.JLabel jlbClassificacao;
    private JNumberField.JNumberField jnf;
    private EditFiled.JNumberLetterField jqtParcelas;
    private javax.swing.JComboBox<String> jtpClassificacao;
    private JNumberField.JNumberField jvlTotal;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel4;
    // End of variables declaration//GEN-END:variables

    private void carregaTabela() {
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.setNumRows(0);
        
        for (Conta conta : contasGerar) {
            dm.setNumRows(dm.getRowCount()+1);
            if (conta.getQtParcela() == 1){
                dm.setValueAt("1x", dm.getRowCount()-1, 0);
            } else {
                dm.setValueAt(conta.getNrParcela() + "/" + conta.getQtParcela(), dm.getRowCount()-1, 0);
            }
            try {
                dm.setValueAt(Pandora.LD_STR(conta.getDtVencimento()), dm.getRowCount()-1, 1);
            } catch (Exception e) {
            }
            jnf.setValue(conta.getVlDebito());
            dm.setValueAt(jnf.getText(), dm.getRowCount()-1, 2);
            
        }
    }
    
    
    
    private void calculaParcelas(){
        try {
            
            contasGerar = new ArrayList<>();
            
            if (jdtDigitacao.getText().equals("")){
                carregaTabela();
                return;
            }
            if (jdtPrimeiroVenc.getText().equals("")){
                carregaTabela();
                return;
            }
            if (jvlTotal.getValue() == BigDecimal.ZERO){
                carregaTabela();
                //return;
            }
            if (jqtParcelas.getText().equals("")){
                carregaTabela();
                return;
            }
            
            
            LocalDate dtDigitacao = Pandora.STR_LD(jdtDigitacao.getText());
            LocalDate dtPriVenc = Pandora.STR_LD(jdtPrimeiroVenc.getText());
            BigDecimal vlTitulo  = jvlTotal.getValue();
            int qtParc = Integer.parseInt(jqtParcelas.getText());
            BigDecimal qtParcela = BigDecimal.valueOf(qtParc);
        
            
            
            
            
            
            Conta conta;
            double valorParcela = jvlTotal.getValue().doubleValue() / qtParc;
            jnf.setValue(BigDecimal.valueOf(valorParcela));
            valorParcela = jnf.getValue().doubleValue();
            double valorSaldo = jvlTotal.getValue().doubleValue() - (valorParcela*qtParc);
            
            LocalDate dataAux;
            dataAux = Pandora.STR_LD(jdtPrimeiroVenc.getText());
            for (int i = 0; i < qtParc; i++) {
                        
                        
                conta = new Conta();
                conta.setNrParcela(i+1);
                conta.setQtParcela(qtParc);
                conta.setTpMovimento("Entrada");
                conta.setTpSituacao("Aberto");
                conta.setIdPessoa(1L);
                conta.setNmCliConta("WAGNER ALMEIDA SILVEIRA");
                if (dtDigitacao.isEqual(LocalDate.now())){
                    conta.setDtTransacao(LocalDateTime.now());
                } else {
                    conta.setDtTransacao(LocalDateTime.of(dtPriVenc, LocalTime.of(0, 0)));
                }
                //conta.setDtVencimento(LocalDate.now().plusDays(30*(i+1)));
                conta.setDtVencimento(dataAux);
                dataAux = dataAux.plusDays(30);
                
                
                if (i == (qtParc-1)){//ultima parcela (adiconar saldo)
                    conta.setVlDebito(BigDecimal.valueOf(valorParcela + valorSaldo));
                } else {
                    conta.setVlDebito(BigDecimal.valueOf(valorParcela));
                }
                conta.setDsObs(jdsObs.getText());
                conta.setTpOrigem("Manual");
                conta.setInExcluido(false);
                contasGerar.add(conta);
            }
                
            
            
            
        } catch (Exception e) {
            Pandora.ex(e);
        }
        
        carregaTabela();
        
    }

    private void iniciaTela() throws Exception {
        jnf.setVisible(false);
        jtpClassificacao.setVisible(false);
        jlbClassificacao.setVisible(false);
        jdtDigitacao.setText(Pandora.LD_STR(LocalDate.now()));
        jdtPrimeiroVenc.setText(Pandora.LD_STR(LocalDate.now().plusDays(30)));
        jqtParcelas.setText("1");
        jvlTotal.setValue(BigDecimal.ZERO);
        
        calculaParcelas();
        
    }
}
