/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.qualix.financeiro.visao;

import br.com.qualix.aaaFerramentas.Pandora;
import br.com.qualix.financeiro.modelo.Recibo;
import br.com.qualix.financeiro.modelo.ReciboItens;
import br.com.qualix.financeiro.modelo.ReciboPagamento;
import br.com.qualix.financeiro.modelo.TipoPagamento;
import br.com.qualix.orcamento.visao.FQtParcela;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wagner
 */
public class FInformarPagamento extends javax.swing.JFrame {

    ArrayList<ReciboItens> itens = new ArrayList<>();
    Recibo recibo = new Recibo();
    
    
    /**
     * Creates new form FInformarPagamento
     */
    public FInformarPagamento(Map params) {
        initComponents();
        
        if (params != null){
            

            itens = (ArrayList<ReciboItens>) params.get("reciboitens");
            recibo = (Recibo) params.get("recibo");

            
            DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
            dm.setNumRows(0);
            for (ReciboItens item : itens) {
                dm.setNumRows(dm.getRowCount()+1);
                try {
                    dm.setValueAt(item.getIdConta(), dm.getRowCount()-1, 0);
                    dm.setValueAt(Pandora.LD_STR(item.getDtVencimento()), dm.getRowCount()-1, 1);
                    jnf.setValue(item.getVlPagamento());
                    dm.setValueAt(jnf.getText(), dm.getRowCount()-1, 2);
                } catch (Exception e) {
                    
                }
            }
            
            
        } else {
            
        }
      
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jNumberLetterField1 = new EditFiled.JNumberLetterField();
        jLabel2 = new javax.swing.JLabel();
        jNumberLetterField2 = new EditFiled.JNumberLetterField();
        jLabel3 = new javax.swing.JLabel();
        jNumberField1 = new JNumberField.JNumberField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jbtPgDinheiro = new javax.swing.JButton();
        jbtPgPix = new javax.swing.JButton();
        jbtPgCredito = new javax.swing.JButton();
        jbtPgDebito = new javax.swing.JButton();
        jbtPgCrediario = new javax.swing.JButton();
        jvlPagamento = new JNumberField.JNumberField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jnf = new JNumberField.JNumberField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informar Pagamento");

        jLabel1.setText("Id Pagamento");

        jNumberLetterField1.setText("jNumberLetterField1");

        jLabel2.setText("Observação");

        jNumberLetterField2.setText("jNumberLetterField2");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Valor");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable2.setRowHeight(25);
        jScrollPane2.setViewportView(jTable2);

        jPanel5.setBackground(new java.awt.Color(230, 230, 230));

        jbtPgDinheiro.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtPgDinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pgdinheiro.png"))); // NOI18N
        jbtPgDinheiro.setText("Dinheiro");
        jbtPgDinheiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPgDinheiro.setPreferredSize(new java.awt.Dimension(73, 57));
        jbtPgDinheiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPgDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPgDinheiroActionPerformed(evt);
            }
        });

        jbtPgPix.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtPgPix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pgpix.png"))); // NOI18N
        jbtPgPix.setText("PIX");
        jbtPgPix.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPgPix.setPreferredSize(new java.awt.Dimension(73, 57));
        jbtPgPix.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPgPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPgPixActionPerformed(evt);
            }
        });

        jbtPgCredito.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtPgCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pgcredit.png"))); // NOI18N
        jbtPgCredito.setText("Crédito");
        jbtPgCredito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPgCredito.setPreferredSize(new java.awt.Dimension(73, 57));
        jbtPgCredito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPgCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPgCreditoActionPerformed(evt);
            }
        });

        jbtPgDebito.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtPgDebito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pgdebit.png"))); // NOI18N
        jbtPgDebito.setText("Débito");
        jbtPgDebito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPgDebito.setPreferredSize(new java.awt.Dimension(73, 57));
        jbtPgDebito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPgDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPgDebitoActionPerformed(evt);
            }
        });

        jbtPgCrediario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtPgCrediario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pgcrediatrio.png"))); // NOI18N
        jbtPgCrediario.setText("Crediário");
        jbtPgCrediario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPgCrediario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPgCrediario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPgCrediarioActionPerformed(evt);
            }
        });

        jLabel8.setText("Valor:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jbtPgDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtPgPix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtPgCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtPgDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtPgCrediario)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jvlPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jvlPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtPgCrediario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPgDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPgPix, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPgCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPgDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jnf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNumberLetterField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNumberLetterField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNumberField1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumberLetterField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNumberLetterField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtPgDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPgDinheiroActionPerformed
        if (jvlPagamento.getValue() != BigDecimal.ZERO){
            TipoPagamento tipo = new TipoPagamento(1l, "DINHEIRO", 0);
            ReciboPagamento recPag = new ReciboPagamento(null, tipo, jvlPagamento.getValue());
            DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
            dm.setNumRows(dm.getRowCount()+1);
            dm.setValueAt(recPag, dm.getRowCount()-1, 0);
            jnf.setValue(recPag.getVlPagamento());
            dm.setValueAt(jnf.getText(), dm.getRowCount()-1, 1);
            jvlPagamento.setValue(BigDecimal.ZERO);
            //atualizaTotalizadores();
        }
    }//GEN-LAST:event_jbtPgDinheiroActionPerformed

    private void jbtPgPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPgPixActionPerformed
        if (jvlPagamento.getValue() != BigDecimal.ZERO){
            TipoPagamento tipo = new TipoPagamento(4l, "PIX", 0);
            ReciboPagamento pedPag = new ReciboPagamento(null, tipo, jvlPagamento.getValue());
            DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
            dm.setNumRows(dm.getRowCount()+1);
            dm.setValueAt(pedPag, dm.getRowCount()-1, 0);
            jnf.setValue(pedPag.getVlPagamento());
            dm.setValueAt(jnf.getText(), dm.getRowCount()-1, 1);
            jvlPagamento.setValue(BigDecimal.ZERO);
            //atualizaTotalizadores();
        }
    }//GEN-LAST:event_jbtPgPixActionPerformed

    private void jbtPgCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPgCreditoActionPerformed
        if (jvlPagamento.getValue() != BigDecimal.ZERO){

            //String opt = JOptionPane.showInputDialog("Quantidade de Parcelas");
            FQtParcela box = new FQtParcela(this, true);
            box.addWindowListener(new WindowAdapter() {
                public void windowClosed(WindowEvent e) {

                    TipoPagamento tipo = new TipoPagamento(2l, "CREDITO", box.qtde);
                    ReciboPagamento pedPag = new ReciboPagamento(null, tipo, jvlPagamento.getValue());
                    DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
                    dm.setNumRows(dm.getRowCount()+1);
                    dm.setValueAt(pedPag, dm.getRowCount()-1, 0);
                    jnf.setValue(pedPag.getVlPagamento());
                    dm.setValueAt(jnf.getText(), dm.getRowCount()-1, 1);
                    jvlPagamento.setValue(BigDecimal.ZERO);
                    //atualizaTotalizadores();

                }

            });
            box.setVisible(true);

        }
    }//GEN-LAST:event_jbtPgCreditoActionPerformed

    private void jbtPgDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPgDebitoActionPerformed
        if (jvlPagamento.getValue() != BigDecimal.ZERO){
            TipoPagamento tipo = new TipoPagamento(3l, "DEBITO", 0);
            ReciboPagamento pedPag = new ReciboPagamento(null, tipo, jvlPagamento.getValue());
            DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
            dm.setNumRows(dm.getRowCount()+1);
            dm.setValueAt(pedPag, dm.getRowCount()-1, 0);
            jnf.setValue(pedPag.getVlPagamento());
            dm.setValueAt(jnf.getText(), dm.getRowCount()-1, 1);
            jvlPagamento.setValue(BigDecimal.ZERO);
            //atualizaTotalizadores();
        }
    }//GEN-LAST:event_jbtPgDebitoActionPerformed

    private void jbtPgCrediarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPgCrediarioActionPerformed
        if (jvlPagamento.getValue() != BigDecimal.ZERO){

            TipoPagamento tipo = new TipoPagamento(6l, "CREDIARIO", 0);
            ReciboPagamento pedPag = new ReciboPagamento(null, tipo, jvlPagamento.getValue());
            DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
            dm.setNumRows(dm.getRowCount()+1);
            dm.setValueAt(pedPag, dm.getRowCount()-1, 0);
            jnf.setValue(pedPag.getVlPagamento());
            dm.setValueAt(jnf.getText(), dm.getRowCount()-1, 1);
            jvlPagamento.setValue(BigDecimal.ZERO);
            //atualizaTotalizadores();
        }
    }//GEN-LAST:event_jbtPgCrediarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FInformarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FInformarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FInformarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FInformarPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FInformarPagamento(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private JNumberField.JNumberField jNumberField1;
    private EditFiled.JNumberLetterField jNumberLetterField1;
    private EditFiled.JNumberLetterField jNumberLetterField2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtPgCrediario;
    private javax.swing.JButton jbtPgCredito;
    private javax.swing.JButton jbtPgDebito;
    private javax.swing.JButton jbtPgDinheiro;
    private javax.swing.JButton jbtPgPix;
    private JNumberField.JNumberField jnf;
    private JNumberField.JNumberField jvlPagamento;
    // End of variables declaration//GEN-END:variables
}
